# Generated by Django 5.2.2 on 2026-02-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
