# Generated by Django 5.2.2 on 2026-02-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_company_isactive_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
